theme: jekyll-theme-minimal
title: Dominic Thomas
description: Data Scientist in the DC area publishing ~~mostly nonsense that sometimes is correlated with the whole "Data Science" thing~~ previous works and projects.
